 chủ đề  const =  [
    {
        loại : 'Động' ,
        danh sách : [
            {
                name : 'Tối' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/dark.jpg' ,
                chi tiết : {
                    chínhBg : "#1e1e1e" ,
                    menuSideBg : "#292929" ,
                    nhạcPlayBg : "#181818" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#4c5262" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#282828" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            } ,
            {
                name : 'Xanh Da Trời' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/dynamic-blue.jpg' ,
                chi tiết : {
                    chínhBg : "#101f3f" ,
                    menuSideBg : "#1c2a49" ,
                    nhạcPlayBg : "#0a1835" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#565e70" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#192f60" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            } ,
            {
                tên : 'Hồng' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/dynamic-pink.jpg' ,
                chi tiết : {
                    chínhBg : "#800064" ,
                    menuSideBg : "#9b2180" ,
                    nhạcPlayBg : "#660050" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#dadada" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#f80" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#a22687" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            } ,
            {
                name : 'Nâu' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/dynamic-brown.jpg' ,
                chi tiết : {
                    chínhBg : "#57403b" ,
                    menuSideBg : "#604a45" ,
                    nhạcPlayBg : "#46332f" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#d7d7d6" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#6f514c" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            } ,
            {
                name : 'Hồng Cánh Sen' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/pink-light.jpg' ,
                chi tiết : {
                    chínhBg : "#f9dbdb" ,
                    menuSideBg : "#fbe6e6" ,
                    nhạcPlayBg : "#f9c6c5" ,
                    borderLayout : "#afb9b9" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#289595" ,
                    activeColor : "#012658" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    textColor : "#32323d" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#e1e8e8" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            }
        ]
    } ,
    {
        gõ : 'Color Sắc' ,
        danh sách : [
            {
                name : 'Tím' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/purple.jpg' ,
                chi tiết : {
                    chínhBg : "#170f23" ,
                    menuSideBg : "#231b2e" ,
                    nhạcPlayBg : "#120c1c" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#4c5262" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#432275" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            } ,
            {
                name : 'Đỏ' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/red.jpg' ,
                chi tiết : {
                    chínhBg : "#731717" ,
                    menuSideBg : "#7a2323" ,
                    nhạcPlayBg : "#5c1212" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#7885a8" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#883236" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            } ,
            {
                name : 'Xanh Lá' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/blue.jpg' ,
                chi tiết : {
                    chínhBg : "#124534" ,
                    menuSideBg : "#1e4e3e" ,
                    nhạcPlayBg : "#0e372a" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#bec5c2" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#126e54" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            } ,
            {
                name : 'Xanh Biển' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/blue-light.jpg' ,
                chi tiết : {
                    chínhBg : "#1d375a" ,
                    menuSideBg : "#294162" ,
                    nhạcPlayBg : "#172c48" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#5d6c7f" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#274a78" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            } ,
            {
                name : 'Xanh Nhạt' ,
                hình thu nhỏ : 'https://zmp3-static.zmdcdn.me/skins/zmp3-v6.1/images/theme/green-light.jpg' ,
                chi tiết : {
                    chínhBg : "#ced9d9" ,
                    menuSideBg : "#dde4e4" ,
                    nhạcPlayBg : "#b4d0d0" ,
                    borderLayout : "#afb9b9" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#289595" ,
                    activeColor : "#012658" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    textColor : "#32323d" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#e1e8e8" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
            }
        ]
    } ,
    {
        gõ : "Ca Sĩ" ,
        danh sách : [
            {
                tên : 'Justin Bieber' ,
                hình thu nhỏ : './assets/img/thumbnail_justinbieber.png' ,
                chi tiết : {
                    chínhBg : "#170f23" ,
                    menuSideBg : "#231b2e" ,
                    nhạcPlayBg : "#120c1c" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#4c5262" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#432275" ,
                    backgroundImage : "url('../img/bg_justinbieber.png')"
                }
                
            } ,
            {
                name : 'Rose (Blackpink)' ,
                hình thu nhỏ : './assets/img/thumbnail_rose.png' ,
                chi tiết : {
                    chínhBg : "#170f23" ,
                    menuSideBg : "#231b2e" ,
                    nhạcPlayBg : "#120c1c" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#4c5262" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#432275" ,
                    hình nền : "url('../img/bg_rose.png')"
                }
                
            } ,
            {
                name : 'Nguyễn Văn Giàu' ,
                hình thu nhỏ : './assets/img/thumbnail_vangiau.png' ,
                chi tiết : {
                    chínhBg : "#170f23" ,
                    menuSideBg : "#231b2e" ,
                    nhạcPlayBg : "#120c1c" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#4c5262" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#432275" ,
                    backgroundImage : "url('../img/bg_vangiau.png')"
                }
                
            } ,
            {
                name : 'Sơn Tùng MTP' ,
                hình thu nhỏ : './assets/img/thumbnail_sontungmtp.png' ,
                chi tiết : {
                    chínhBg : "#170f23" ,
                    menuSideBg : "#231b2e" ,
                    nhạcPlayBg : "#120c1c" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#4c5262" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#432275" ,
                    hình nền : "url('../img/bg_sontungmtp.png')"
                }
                
            } ,
            {
                tên : 'Rắn DJ' ,
                hình thu nhỏ : './assets/img/thumbnail_djsnake.png' ,
                chi tiết : {
                    chínhBg : "#170f23" ,
                    menuSideBg : "#231b2e" ,
                    nhạcPlayBg : "#120c1c" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#4c5262" ,
                    activeColor : "#36e2ec" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#432275" ,
                    hình nền : "url('../img/bg_djsnake.png')"
                }
                
            }
        ]
    } ,
    {
        loại : "Độ dốc" ,
        danh sách : [
            {
                tên : 'Kaki Aquamarine' ,
                hình thu nhỏ : './assets/img/thumbnail_gradient_1.png' ,
                chi tiết : {
                    PrimaryBg : "linear-gradient(45deg, #85FFBD 0%, #FFFB7D 100%)" ,
                    menuSideBg : "#8cffba" ,
                    nhạcPlayBg : "#fcfb7e" ,
                    borderLayout : "#afb9b9" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#289595" ,
                    activeColor : "#012658" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    textColor : "#32323d" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#e1e8e8" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
                
            } ,
            {
                name : 'Sandy Brown Violet' ,
                hình thu nhỏ : './assets/img/thumbnail_gradient_2.png' ,
                chi tiết : {
                    PrimaryBg : "độ dốc tuyến tính (102,4deg, rgba(253,189,85,1) 7,8%, rgba(249,131,255,1) 100,3% )" ,
                    menuSideBg : "#fcb371" ,
                    musicPlayBg : "độ dốc tuyến tính (102,4deg, rgba(253,289,85,1) 7,8%, rgba(149,131,255,1) 100,3% )" ,
                    borderLayout : "#afb9b9" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#289595" ,
                    activeColor : "#012658" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    textColor : "#32323d" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#e1e8e8" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
                
            } ,
            {
                tên : 'Xanh lam đậm' ,
                hình thu nhỏ : './assets/img/thumbnail_gradient_3.png' ,
                chi tiết : {
                    PrimaryBg : "radial-gradient( circle 963px ở 1,9% 5%, rgba(0,193,80,1) 0%, rgba(0,112,198,1) 100,2% )" ,
                    menuSideBg : "linear-gradient(to bottom, #00c052, #00968e)" ,
                    musicPlayBg : "linear-gradient(sang phải, #0070c0, #00ab70)" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#4e4e83" ,
                    activeColor : "#08143d" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#23181c" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#126e54" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
                
            } ,
            {
                tên : 'Cà chua nâu' ,
                hình thu nhỏ : './assets/img/thumbnail_gradient_4.png' ,
                chi tiết : {
                    PrimaryBg : "độ dốc tuyến tính (135deg, #F05F57 10%, #360940 100%)" ,
                    menuSideBg : "linear-gradient( to bottom, #f05f57, #6f2448)" ,
                    musicPlayBg : "độ dốc tuyến tính (sang phải, #802c4a, #bc4750)" ,
                    borderLayout : "hsla(0,0%,100%,0,1)" ,
                    borderDivideElement : "rgb(47, 47, 77)" ,
                    greenBanana : "#62c06e" ,
                    greenColor : 	 "#2E8B57" ,
                    xanh đậm : "# 246e44 " ,
                    darkCyan : "#109db6" ,
                    xanh đậm : "# 0000d8 " ,
                    noneActiveColor : "#0dd6f1" ,
                    activeColor : "#ff9" ,
                    màu hồng : "# fc5c7d " ,
                    blueColor : "#6a82fb" ,
                    màu bạc : 	 "#C0C0C0" ,
                    văn bảnColor : "#fff" ,
                    subTextColor : "#9a9798" ,
                    camColor : "#fa8b26" ,
                    xanhViolet : "#a742c6" ,
                    themeModalBg : "#883236" ,
                    backgroundImage : "url('../img/bg_mainpage.png')"
                }
                
            }
        ]
    }
    
    
]
